### ISSUE TITLE
Вызов call возращает null

### ISSUE THREAD

**Issue by alpacas9** [wielski/KinopoiskApi#6]
Здравствуйте. Спасибо за труд! У меня проблема при работе с php. Функция call возращает null. Сама функция callMethod на метод getFilm возвращает false. В чем может быть проблема? Спасибо.

**Comment by coolswitcher** [comment]
Юзай прокси

**Comment by alpacas9** [comment]
Проблема не в прокси. На разных ip получил такую же проблему. Ладно, вопрос закрыт. Нашел решение для своей задачи.
